title: A Bunch of Random Tech Articles
description: Mostly for myself, but feel free to browse around.
show_downloads: false
google_analytics: 
remote_theme: jekyll/minima
permalink: /:title:output_ext