remote_theme: jekyll/minima

title: Nicolas Barraud's Blog

description: I'm the founder at Airbadge, a virtual office for remote teams.

author:
  name: Nicolas Barraud
  email: nicolas@airbadge.com
  website:
    name: Airbadge
    url: https://www.airbadge.com

show_excerpts: false

permalink: /:title:output_ext

google_analytics: G-78CXCX9H4J

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    linkedin: nicolas-barraud

disqus:
    shortname: nicolasbarraudblog

plugins:
 - jekyll-feed
 - jekyll-seo-tag