remote_theme: jekyll/minima

title: Nicolas Barraud's Blog

author:
  name: Nicolas Barraud
  email: nicolas@airbadge.com

description: I'm the founder at Airbadge.com, a virtual office for remote teams. I write this blog as a personal knowledge base, and hopefully to help out a few fellow developers.

show_excerpts: false

permalink: /:title:output_ext

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    linkedin: nicolas-barraud

disqus:
    shortname: nicolasbarraudblog

plugins:
 - jekyll-feed
 - jekyll-seo-tag