title: A Bunch of Random Tech Articles
description: Mostly for myself and possibly you.
github:
  is_project_page: false
show_downloads: false
google_analytics: 
theme: jekyll-theme-cayman
permalink: /:title:output_ext